- name: mac setup
  hosts: localhost
  connection: local

  vars:
    homebrew_cask_packages:
      - name: appcleaner
      - name: arc
      - name: cursor
      - name: dbeaver-community
      - name: discord
      - name: docker
      - name: google-chrome
      - name: google-japanese-ime
      - name: hiddenbar
      - name: notion
      - name: raycast
      - name: slack
      - name: warp

    homebrew_packages:
      - name: awscli
      - name: git
      - name: jq
      - name: mas
      - name: mise

    mas_packages:
      - {id: 539883307, name: LINE}

  tasks:
    - name: homebrew update
      community.general.homebrew:
        update_homebrew: true

    - name: homebrew packages install
      community.general.homebrew:
        name: '{{ item.name }}'
        state: present
      with_items: '{{ homebrew_packages }}'

    - name: homebrew cask packages install
      community.general.homebrew_cask:
        name: '{{ item.name }}'
        state: present
        install_options:
          - '--appdir=/Applications'
      with_items: '{{ homebrew_cask_packages }}'

    - name: mas packages install
      community.general.mas:
        id: '{{ item.id }}'
        state: present
      with_items: '{{ mas_packages }}'

    # - name: setup mise shell initialization
    #   blockinfile:
    #     path: ~/.zshrc
    #     marker: "# {mark} ANSIBLE MANAGED BLOCK - mise"
    #     block: |
    #       eval "$(mise activate zsh)"
    #     create: yes
    #   when: "'mise' in homebrew_packages | map(attribute='name') | list"
