- name: mac setup
  hosts: localhost
  connection: local

  vars:
    homebrew_taps:
      - homebrew/core

    homebrew_cask_packages:
      - name: appcleaner
      - name: docker
      - name: dozer
      - name: firefox
      - name: google-chrome
      - name: iterm2
      - name: macupdater
      - name: raycast
      - name: skitch
      - name: slack
      - name: sourcetree
      - name: visual-studio-code
      - name: warp

    homebrew_packages:
      - name: awscli
      - name: git
      - name: jq
      - name: mas

    mas_packages:
      - {id: 539883307, name: LINE}
      - {id: 441258766, name: Magnet}
      - {id: 568494494, name: Pocket}
      - {id: 1176895641, name: Spark}

  tasks:
    - name: homebrew update
      homebrew:
        update_homebrew: yes

    - name: homebrew tap
      homebrew_tap:
        name: '{{ item }}'
        state: present
      with_items: '{{ homebrew_taps }}'

    - name: homebrew cask packages install
      homebrew_cask: name={{ item.name }} state=installed
      # ※1 GUIツールをインストールする場所を `/Application` に固定
      environment:
        HOMEBREW_CASK_OPTS: "--appdir=/Applications"
      with_items: '{{ homebrew_cask_packages }}'

    - name: homebrew packages install
      homebrew:
        name: '{{ item.name }}'
        state: '{{ item.state | default("present") }}'
      with_items: '{{ homebrew_packages }}'

    - name: mas packages install
      shell: mas install {{ item.id }}
      with_items: '{{ mas_packages }}'
